#SERVER
server:
  port: 3005

#SQL
spring:
  application:
    name: 'idiomas'

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/c3_language?createDatabaseIfNotExist=true&useSSL=false
    username: postgres
    password: admin

    # JPA properties
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true

eureka:
  instance:
    hostname: idiomasc3app.herokuapp.com
    nonSecurePort: 80
  client:
    service-url:
      defaultZone: https://eurekaserverc3.herokuapp.com/eureka/

